
name: Run test suite on code base
author: Christian Wolf <github@christianwolf.email>
description: <
    This is a github action to test the cookbook Nextcloud app.

inputs:
    phpVersion:
        description: The PHP version to use for the tests
        required: false
        default: '7'
    db:
        description: The db type to use
        required: true

runs:
    using: 'composite'
    steps:
        -   run: docker build -t docker-tests --build-arg PHPVERSION=${{ inputs.phpVersion }} $(pwd)/nextcloud/custom_apps/cookbook/.github/actions/run-tests/tests
            name: Build the test image
            shell: bash
        -   run: docker run -e INPUT_DB -v "$GITHUB_WORKSPACE":/workdir docker-tests
            name: Run the test container
            shell: bash
            
