
name: Run test suite on code base
author: Christian Wolf <github@christianwolf.email>
description: <
    This is a github action to test the cookbook Nextcloud app.

inputs:
    phpVersion:
        description: The PHP version to use for the tests
        required: false
        default: '7'
    db:
        description: The db type to use
        required: true

runs:
    using: 'composite'
    steps:
        -   run: docker build -t docker-tests --build-arg PHPVERSION=${{ inputs.phpVersion }} $(pwd)/nextcloud/custom_apps/cookbook/.github/actions/run-tests/tests
            name: Build the test image
            shell: bash
        -   run: <
                docker run 
                -e INPUT_DB
                -e GITHUB_ACTIONS
                -e GITHUB_WORKFLOW
                -e GITHUB_RUN_ID
                -e GITHUB_RUN_NUMBER
                -e GITHUB_ACTION
                -e GITHUB_ACTOR
                -e GITHUB_REPOSIITORY
                -e GITHUB_EVENT_NAME
                -e GITHUB_EVENT_PATH
                -e GITHUB_WORKSPACE=/workdir
                -e GITHUB_SHA
                -e GITHUB_REF
                -e GITGUB_HEAD_REF
                -e GITHUB_BASE_REF
                -e GITHUB_SERVER_URL
                -e GITHUB_API_URL
                -e GITHUB_GRAPHQL_URL
                -e CI
                -v "$GITHUB_WORKSPACE":/workdir
                docker-tests
            name: Run the test container
            shell: bash
            
