version: "3.1"

services:
    mysql:
        build: mysql
        volumes:
            - ./volumes/mysql:/var/lib/mysql
        env_file:
            - mysql.env
            
    postgres:
        image: postgres:alpine
        env_file:
            - postgres.env
        volumes:
            - ./volumes/postgres:/var/lib/postgresql/data
    
    dut: &dut
        image: nextcloudcookbook/testci:php${PHP_VERSION}
        build:
            context: ./tests
            #args:
                #PHPVERSION: 7
                #UID: 1000
        environment:
            INPUT_DB:
            ALLOW_FAILURE:
            HTTP_SERVER:
            GITHUB_WORKSPACE:
            CI:
            RUNNER_UID:
            RUNNER_GID:
            #GITHUB_ACTIONS
            #GITHUB_WORKFLOW
            #GITHUB_RUN_ID
            #GITHUB_RUN_NUMBER
            #GITHUB_ACTION
            #GITHUB_ACTOR
            #GITHUB_REPOSIITORY
            #GITHUB_EVENT_NAME
            #GITHUB_EVENT_PATH
            #GITHUB_SHA
            #GITHUB_REF
            #GITGUB_HEAD_REF
            #GITHUB_BASE_REF
            #GITHUB_SERVER_URL
            #GITHUB_API_URL
            #GITHUB_GRAPHQL_URL
        env_file:
            - mysql.env
            - postgres.env
        volumes:
            - ../../..:/cookbook:ro
            - ./volumes/nextcloud:/nextcloud
            - ./volumes/data:/nextcloud/data
            - ./volumes/cookbook:/nextcloud/apps/cookbook
            - ./volumes/dumps:/dumps
            - ./volumes/coverage:/coverage
            - ./volumes/www/:/www
    
    occ:
        <<: *dut
        entrypoint: ["/entrypoints/default-entrypoint.sh", "/entrypoints/occ.sh"]
        
    php:
        <<: *dut
        entrypoint: ["php"]
    
    fpm:
        <<: *dut
        entrypoint: ["/usr/bin/tini", "--", "/entrypoints/default-entrypoint.sh", "docker-php-entrypoint"]
        command: ['php-fpm']
        user: root
    
    apache:
        image: httpd:alpine
        volumes:
            - ./config/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
            - ./volumes/nextcloud:/nextcloud:ro
            - ./volumes/data:/nextcloud/data:ro
            - ./volumes/cookbook:/nextcloud/apps/cookbook:ro
    
    nginx:
        image: nginx:alpine
        #command: [nginx-debug, '-g', 'daemon off;']
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./volumes/nextcloud:/nextcloud:ro
            - ./volumes/data:/nextcloud/data:ro
            - ./volumes/cookbook:/nextcloud/apps/cookbook:ro
        
    www:
        image: nginx:alpine
        volumes:
            - ./volumes/www/:/usr/share/nginx/html:ro
