
name: CI-tests

on:
  push:
  pull_request:

jobs:
  
  test:
    name: Run the unittests
    runs-on: ubuntu-latest
    
    strategy:
        matrix:
            database:
                - mysql
                - pgsql
                - sqlite
            coreVersion:
                - stable19
            phpVersion:
                - "7"
            include:
                # Test different core versions additionally
                -   database: mysql
                    coreVersion: stable18
                    phpVersion: "7"
                -   database: mysql
                    coreVersion: stable20
                    phpVersion: "7"
                
                # Test different PHP versions additionally
                -   database: mysql
                    coreVersion: stable19
                    phpVersion: "7.1"
                -   database: mysql
                    coreVersion: stable19
                    phpVersion: "5.6"
                    
    steps:
      - name: Checkout the nextcloud server
        uses: actions/checkout@v2
        with:
            repository: nextcloud/server
            ref: ${{ matrix.coreVersion }}
            path: nextcloud
      - name: Checkout the app
        uses: actions/checkout@v2
        with:
            path: nextcloud/custom_apps/cookbook
      
      #- name: Docker Layer Caching
        #uses: satackey/action-docker-layer-caching@v0.0.8
        
      - name: Run the tests in docker container
        uses: ./nextcloud/custom_apps/cookbook/.github/actions/run-tests
        with:
            db: ${{ matrix.database }}
            phpVersion: ${{ matrix.phpVersion }}
