
name: CI-tests

on:
  push:
  pull_request:

jobs:
  
  test:
    name: Run the unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the nextcloud server
        uses: actions/checkout@v2
        with:
            repository: nextcloud/server
            ref: stable19
            path: nextcloud
      - name: Checkout the app
        uses: actions/checkout@v2
        with:
            path: nextcloud/custom_apps/cookbook
      
      #- name: Docker Layer Caching
        #uses: satackey/action-docker-layer-caching@v0.0.8
        
      - name: Save the WORKSPACE on the host runner
        run: echo ::set-output name=hostWorkspace::$GITHUB_WORKSPACE
        id: workspace
        
      - name: Run the tests in docker container
        uses: ./nextcloud/custom_apps/cookbook/.github/actions/run-tests
        with:
            db: mysql
            hostWorkspace: ${{ steps.workspace.outputs.hostWorkspace }}
