
name: CI-tests

on:
  push:
  pull_request:

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the nextcloud server
        uses: actions/checkout@v2
        with:
            repository: nextcloud/server
            ref: stable19
            path: nextcloud
      - name: Checkout the app
        uses: actions/checkout@v2
        with:
            path: nextcloud/custom_apps/cookbook
        
      - name: Run the tests in docker container
        uses: ./nextcloud/custom_apps/cookbook/.github/actions/run-tests
        with:
            db: mysql
